### PR TITLE
Adds MyPortifolio Widget

### PR DESCRIPTION
**Pull request by Moejoe90**
- [x] MyNeuWidget in case of a new user
- [x] MyNeuWidget in case of a user with Money
- [x] MyPortolio Welcome 
- [ ] MyPortolio tables
- [x] Desktop 
- [x] Tablet 
- [x] Mobile
- [ ] Background ICON!

image

image

### CODE REVIEW

**Comment by lizonp** [comment]
@Moejoe90 It doesn't looks well on iphone se resolution (320px), also fonts have different weights, sizes and color on designs (zpl://screen?sid=5a9e5b094c4bf91e31716da6&pid=5a8a92c89c1a166a6a6e8f37)

**Comment by Moejoe90** [comment]
@lizonp the designs are based on a 360px

**Comment by krzkaczor** [comment]
@lizonp @Moejoe90 yeah i think we agreed that the lowest supported resolution will be 360px.

**Comment by huesforalice** [comment]
One other suggestion would be to call the text size classes 
small-text
medium-text
large-text

or something like that, we can batch refactor this later though.

**Comment by Moejoe90** [comment]
you mean from MyPortfolioWidget to MyPortfolioWidget :D

**Pull request merged**
