### PR TITLE
#4500 Lock screen basic implementation

### PR DESCRIPTION
**Pull request by desfero**
**Testing notes**
IOS: https://install.appcenter.ms/orgs/Neufund/apps/Neufund-Wallet-MVP-iOS/releases/30
Android: https://install.appcenter.ms/orgs/Neufund/apps/Neufund-Wallet-MVP/releases/26

### CODE REVIEW

**Comment by arjunu** [comment]
@desfero 

There 2 non-blocking issues that occur sporadically if you try to close the app when unlock is in progress:

1. Warning
```
ExceptionsManager.js:179 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in Skeleton (at Asset.tsx:43)
    in RCTView (at View.js:34)
    in View (at Asset.tsx:40)
    in RCTView (at View.js:34)
    in View (at Panel.tsx:36)
    in RCTView (at View.js:34)
    in View (at Shadow.tsx:19)
    in Shadow2 (at Panel.tsx:35)
    in Panel (at Asset.tsx:39)
    in AssetSkeleton (at WalletScreenSkeleton.tsx:15)
    in RCTView (at View.js:34)
    in View (at ScrollView.js:1124)
    in RCTScrollView (at ScrollView.js:1260)
    in ScrollView (at ScrollView.js:1286)
    in ScrollView (at AnimatedScrollView.js:24)
    in ForwardRef (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Screen.tsx:94)
    in RCTView (at View.js:34)
    in View (at KeyboardAvoidingView.js:218)
    in KeyboardAvoidingView (at Screen.tsx:88)
    in Screen (at WalletScreenSkeleton.tsx:12)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at src/index.tsx:85)
    in SafeAreaView (at HeaderScreen.tsx:105)
    in RCTView (at View.js:34)
    in View (at HeaderScreen.tsx:84)
    in HeaderScreen (at WalletScreenSkeleton.tsx:10)
    in WalletScreenLayoutSkeleton (at WalletScreen.tsx:42)
    in WalletScreenSwitch (at onLifecycle.tsx:61)
    in OnLifecycle
    in withProps(OnLifecycle)
    in Connect(withProps(OnLifecycle))
    in Connect(Connect(withProps(OnLifecycle))) (at ErrorBoundary.tsx:37)
    in ErrorBoundary (at ErrorBoundary.tsx:36)
    in Unknown (at SceneView.tsx:98)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:89)
    in EnsureSingleNavigator (at SceneView.tsx:88)
    in SceneView (at useDescriptors.tsx:125)
    in RCTView (at View.js:34)
    in View (at BottomTabView.tsx:38)
    in SceneContent (at BottomTabView.tsx:122)
    in RCTView (at View.js:34)
    in View (at ResourceSavingScene.tsx:44)
    in RCTView (at View.js:34)
    in View (at ResourceSavingScene.tsx:27)
    in ResourceSavingScene (at BottomTabView.tsx:117)
    in RCTView (at View.js:34)
    in View (at screens.native.js:132)
    in ScreenContainer (at BottomTabView.tsx:101)
    in RCTView (at View.js:34)
    in View (at BottomTabView.tsx:100)
    in SafeAreaProviderCompat (at BottomTabView.tsx:99)
    in BottomTabView (at createBottomTabNavigator.tsx:41)
    in BottomTabNavigator (at AppAuthRouterTabs.tsx:50)
    in AppAuthRouterTabs (at SceneView.tsx:98)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:89)
    in EnsureSingleNavigator (at SceneView.tsx:88)
    in SceneView (at useDescriptors.tsx:125)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:190)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:189)
    in RCTView (at View.js:34)
    in View (at Card.tsx:526)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:508)
    in PanGestureHandler (at Card.tsx:501)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:497)
    in RCTView (at View.js:34)
    in View (at Card.tsx:491)
    in Card (at CardContainer.tsx:156)
    in CardContainer (at CardStack.tsx:561)
    in RCTView (at View.js:34)
    in View (at CardStack.tsx:136)
    in MaybeScreen (at CardStack.tsx:554)
    in RCTView (at View.js:34)
    in View (at CardStack.tsx:114)
    in MaybeScreenContainer (at CardStack.tsx:452)
    in CardStack (at StackView.tsx:418)
    in KeyboardManager (at StackView.tsx:416)
    in SafeAreaProviderCompat (at StackView.tsx:413)
    in GestureHandlerRootView (at GestureHandlerRootView.android.js:31)
    in GestureHandlerRootView (at StackView.tsx:412)
    in StackView (at createStackNavigator.tsx:82)
    in StackNavigator (at AppAuthRouter.tsx:21)
    in AppAuthRouter (at App.tsx:46)
```

2. Error (it is caught)
```
Error while loading wallet data:  TypeError: Cannot read property 'userId' of undefined
    at loadWalletDataSaga$ (sagas.js:19)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:271)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at next (redux-saga-core.dev.cjs.js:1161)
    at Object.currCb [as cont] (redux-saga-core.dev.cjs.js:1255)
    at end (redux-saga-core.dev.cjs.js:1016)
    at Object.task.cont (redux-saga-core.dev.cjs.js:840)
    at next (redux-saga-core.dev.cjs.js:1174)
    at currCb (redux-saga-core.dev.cjs.js:1255) undefined
```
Some saga that's calling `loadWalletDataSaga` isn't being cancelled I guess.

Approving PR as these can be addressed as improvements if required.

**Comment by arjunu** [comment]
Also maybe we shouldn't lock the app instantly. I checked banking apps and Metamask, both allow a brief switch.

**Comment by Moejoe90** [comment]
Moved back to draft state until @desfero is back and resumes this PR

**Comment by desfero** [comment]
@arjunu the first warning i have also seen a couple of times but not able to reproduce. The second one i think is fixed, maybe you forgot to rebuild `shared-modules` with latest changes?

I forgot to update ticket given there is no need to implement logout after 5 minutes and i don't see metamask/bank apps are doing that also given in a lot of cases phone is locking automatically. 
I tried to play with `react-native-background-timer` to implement small timeout but i'm not able to configure it properly so it runs timer when app is in background.

**Review by Moejoe90 — APPROVED** [review]

**Pull request merged**
