### PR TITLE
Wait before logging-in

### PR DESCRIPTION
**Pull request by desfero**

### CODE REVIEW

**Comment by desfero** [comment]
first run green

**Comment by desfero** [comment]
second run green

**Comment by desfero** [comment]
third green

**Comment by AlexeyTuboltsev** [comment]
hmm... statistically significant count would be around 100 😁

**Comment by desfero** [comment]
4 green

**Comment by desfero** [comment]
5 green

**Comment by desfero** [comment]
6,7 green

**Pull request merged**
